apiVersion: v1 # Версия API
kind: Pod # Объект, который создаем
metadata:
 name: web # Название Pod
 labels: 
  app: web  # Метки в формате key: value
spec: # Описание Pod
 containers:   # Описание контейнеров внутри Pod
 - name:  hw-nginx # Название контейнера
   image: mrg1790/howework-nginx # Образ из которого создается контейнер
 initContainers:
 - name: wget
   image: busybox:1.31.0
   command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
   volumeMounts:
   - name: app
     mountPath: /app
 volumes:
 - name: app
   emptyDir: {}

